package com.pr7.yataxi.ui

import android.content.Intent
import android.graphics.Color
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.View
import androidx.activity.viewModels
import com.pr7.yataxi.R
import com.pr7.yataxi.data.model.body.RegisterBody
import com.pr7.yataxi.data.model.response.RegisterResponse



import com.pr7.yataxi.databinding.ActivityRegisterBinding
import com.pr7.yataxi.utilits.showlogd
import com.pr7.yataxi.utilits.showtoast
import com.pr7.yataxi.viewmodel.MainViewModel

class RegisterActivity : AppCompatActivity() {
    lateinit var binding: ActivityRegisterBinding
    val mainViewModel: MainViewModel by viewModels()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityRegisterBinding.inflate(layoutInflater)
        setContentView(binding.root)
        window.statusBarColor = Color.parseColor("#FEBD2F")
        //('A'..'z').map { it }.shuffled().subList(0, 4).joinToString("")
        val codes = arrayListOf(
            90,
            91,
            97,
            99
        )
        codes.shuffle()

        binding.apply {
            textinputedittextlastname.setText("test ${('A'..'Z').randomOrNull()} ${(0 until 1000).random()}")
            textinputedittextfirstname.setText("test ${('a'..'z').randomOrNull()} ${(0 until 1000).random()}")
            textinputedittextphonenumberregister.setText("+998${codes.get(0)}${(100 until 999).random()}${(1000 until 9999).random()}")
            textinputedittextpasswordregister.setText("test${(10000 until 99000).random()}autogenerated")
            buttonaclogin2.setOnClickListener {
                startActivity(Intent(this@RegisterActivity, LoginActivity::class.java))
                finish()
            }

            buttonregister.setOnClickListener {
                showtoast(textinputedittextlastname.text.toString())

                mainViewModel.registeruser(
                    RegisterBody(
                        first_name = textinputedittextfirstname.text.toString(),
                        last_name = textinputedittextlastname.text.toString(),
                        password = textinputedittextpasswordregister.text.toString(),
                        phone_number = textinputedittextphonenumberregister.text.toString()
                    )
                )

            }

            mainViewModel.succesregister.observe(this@RegisterActivity) {
                if (it) {
                    progressbarregister.visibility = View.VISIBLE

                } else {
                    progressbarregister.visibility = View.GONE

                }
            }

            mainViewModel.registerResponseLiveData.observe(this@RegisterActivity) {

                when(it){
                    is RegisterResponse->{
                        showlogd(it.first_name)

                        if (it.phone_number!=null){

                            val intent = Intent(this@RegisterActivity, LoginActivity::class.java)
                            intent.apply {
                                putExtra("phone","${textinputedittextphonenumberregister.text.toString()}")
                                putExtra("password","${textinputedittextpasswordregister.text.toString()}")
                            }
                            startActivity(intent)
                            edittextclear()
                            finish()

                        }
                    }
                }




            }
        }


    }


    fun edittextclear(){
        binding.apply {
            textinputedittextlastname.setText("")
            textinputedittextfirstname.setText("")
            textinputedittextphonenumberregister.setText("")
            textinputedittextpasswordregister.setText("")
        }
    }


}